# JDBC
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/splitup?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
hibernate.connection.username=root
hibernate.connection.password=caca1234



# Debug
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.use_sql_comments=false

# Esquema
hibernate.hbm2ddl.auto=update
